<div class="sidebar-menu">
    <div class="user-profile-section">
        <div class="profile-tab text-center">
            <img class="img-lg rounded-circle" src="<?= url("assets/images/faces-clipart/pic-1.png")?>" alt="profile image">
            <h3 class="user-name"><?=$_SESSION['login']?></h3>
            <p class="account-type">Free version</p>
        </div>
    </div>
    <nav class="nav">
        <div class="nav-item active">
            <a href="<?=url_pesquisa("paciente")?>" class="nav-link">
                <i class="menu-icons mdi mdi-home-outline"></i><span class="menu-title">Dashboard</span>
            </a>
        </div>
        <div class="nav-item">
            <a href="<?=url_pesquisa("paciente/rpd")?>" class="nav-link">
                <i class="menu-icons mdi mdi-flash"></i><span class="menu-title">RPD</span>
            </a>
        </div>
        <div class="nav-item">
            <a href="<?=url_pesquisa("paciente/planoacao")?>" class="nav-link">
                <i class="menu-icons mdi mdi-check-all"></i><span class="menu-title text-center">Plano de Ação</span>
            </a>
        </div>
        <div class="nav-item">
            <a href="<?=url_pesquisa("paciente/humor")?>" class="nav-link text-center">
                <i class="menu-icons mdi mdi-emoticon-happy-outline"></i><span class="menu-title">Monitoramento de <br> humor</span>
            </a>
        </div>
    </nav>
    <div class="sidebar-footer">
        <div class="progress-wrapper">
            <div class=" progress-wrapper-inner text-center">
<!--                <p class="progress-title">14 days</p>-->
                free version
            </div>
<!--            <div class="progress progress-md">-->
<!--                <div class="progress-bar" role="progressbar" style="width: 37%" aria-valuenow="37" aria-valuemin="0" aria-valuemax="100"></div>-->
<!--            </div>-->
        </div>
<!--        <button type="button" class="btn btn-inverse-primary btn-block upgrade-button">Upgrade plan</button>-->
    </div>
    <div class="sidebar-footer-bottom">
<!--        <ul>-->
<!--            <li><a href="#">Privacy & Policy</a></li>-->
<!--            <li><a href="#">Help & Guide</a></li>-->
<!--        </ul>-->
        <p>© 2021 - DialogPsi </p>
    </div>
</div>