<div class="navbar">
    <div class="nav-brand-wrapper">
        <ul class="nav">
            <li class="nav-item brand-logo">
                <a href="<?=url_pesquisa("")?>" class="logo text-white text-decoration-none">
<!--                    <img src="--><?//=url("assets/images/logo_9.svg")?><!--" alt="Logo">-->
                    DIALOG
                </a>
            </li>
        </ul>
    </div>
    <div class="navbar-menu-wrapper">
        <ul class="nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <i class="mdi mdi-message-text-outline"></i>
                    <span class="count bg-warning"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="messageDropdown">
                    <a class="dropdown-item py-3 border-bottom">
                        <p class="mb-0 font-weight-medium float-left">You have 4 new notifications </p>
                        <span class="badge badge-pill badge-primary float-right">View all</span>
                    </a>
                    <a class="dropdown-item preview-item py-3">
                        <div class="preview-thumbnail">
                            <i class="mdi mdi-alert m-auto text-primary"></i>
                        </div>
                        <div class="preview-item-content">
                            <h6 class="preview-subject font-weight-normal text-dark mb-1">Application Error</h6>
                            <p class="font-weight-light small-text mb-0"> Just now </p>
                        </div>
                    </a>
                    <a class="dropdown-item preview-item py-3">
                        <div class="preview-thumbnail">
                            <i class="mdi mdi-settings m-auto text-primary"></i>
                        </div>
                        <div class="preview-item-content">
                            <h6 class="preview-subject font-weight-normal text-dark mb-1">Settings</h6>
                            <p class="font-weight-light small-text mb-0"> Private message </p>
                        </div>
                    </a>
                    <a class="dropdown-item preview-item py-3">
                        <div class="preview-thumbnail">
                            <i class="mdi mdi-airballoon m-auto text-primary"></i>
                        </div>
                        <div class="preview-item-content">
                            <h6 class="preview-subject font-weight-normal text-dark mb-1">New user registration</h6>
                            <p class="font-weight-light small-text mb-0"> 2 days ago </p>
                        </div>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="mdi mdi-bell-outline"></i>
                    <span class="count bg-danger"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown dropdown-h-style-1 pb-0" aria-labelledby="notificationDropdown">
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-printer"></i>Print Invoice</a>
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-content-copy"></i>Copy</a>
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-file-document-edit-outline"></i>CSV</a>
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-share-outline"></i>Share</a>
                </div>
            </li>
            <li class="nav-item d-none d-md-flex">
                <a class="nav-link" href="<?=url_pesquisa("logout")?>"><i class="mdi mdi-information-outline mr-2"></i>Help</a>
            </li>
            <li class="nav-item dropdown d-none d-xl-inline-block user-dropdown">
                <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <div class="wrapper d-flex flex-column">
                        <span class="profile-text"><?=$_SESSION['login']?></span>
                        <span class="user-designation">Administrator</span>
                    </div>
                    <div class="display-avatar">AS</div>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                    <div class="dropdown-header text-center">
                        <img class="img-md rounded-circle" src="<?=url("assets/images/faces/face1.jpg")?>" alt="Profile image">
                        <p class="mb-1 mt-3 font-weight-semibold">Allen Moreno</p>
                        <p class="font-weight-light text-muted mb-0">allenmoreno@gmail.com</p>
                    </div>
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-account-outline text-primary"></i> My Profile <span class="badge badge-pill badge-danger">1</span></a>
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-message-text-outline text-primary"></i> Messages</a>
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-calendar-check-outline text-primary"></i> Activity</a>
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-help-circle-outline text-primary"></i> FAQ</a>
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-power text-primary"></i>Sign Out</a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</div>