<div class="navbar">
    <div class="nav-brand-wrapper">
        <ul class="nav">
            <li class="nav-item brand-logo">
                <a href="<?=url_pesquisa("")?>" class="logo text-white text-decoration-none">
                    <img src="<?=url("assets/images/dialog/logo1.png")?>" alt="Logo" style="width: 150px">
                </a>
            </li>
        </ul>
    </div>
    <div class="navbar-menu-wrapper">
        <ul class="nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="mdi mdi-bell-outline"></i>
                    <!--                    <span class="count bg-danger"></span>-->
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown dropdown-h-style-1 pb-0" aria-labelledby="notificationDropdown" >
                    <a class="dropdown-item" href="#"><i class="dropdown-item-icon mdi mdi-information-outline"></i>Sem atualizações</a>
                    <!--                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-content-copy"></i>Copy</a>-->
                    <!--                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-file-document-edit-outline"></i>CSV</a>-->
                    <!--                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-share-outline"></i>Share</a>-->
                </div>
            </li>
            <li class="nav-item dropdown languageDropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="LanguageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <div class="flag-wrapper">
                        <i class="flag-icon flag-icon-br"></i>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-left navbar-dropdown pb-0" aria-labelledby="LanguageDropdown">
                    <a href="#" class="dropdown-item">PORTUGUES<i class="flag-icon ml-auto flag-icon-br"></i></a>
<!--                    <a class="dropdown-item">ESPANHOL<i class="flag-icon ml-auto flag-icon-es"></i></a>-->
<!--                    <a class="dropdown-item">INGLES<i class="flag-icon ml-auto flag-icon-us"></i></a>-->
                </div>
            </li>
            <li class="nav-item dropdown d-none d-xl-inline-block user-dropdown">
                <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <div class="wrapper d-flex flex-column">
                        <span class="profile-text"><?=$_SESSION['usuario']->usu_nome?></span>
                        <span class="user-designation">Paciente</span>
                    </div>
                    <div class="display-avatar">Psi</div>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown" >
                    <div class="dropdown-header text-center">
                        <img class="img-md rounded-circle" src="<?=url("assets/images/faces/face2.jpg")?>" alt="Profile image">
                        <p class="mb-1 mt-3 font-weight-semibold"><?=$_SESSION['usuario']->usu_nome?></p>
                        <p class="font-weight-light text-muted mb-0"><?=$_SESSION['usuario']->usu_email?></p>
                    </div>
                    <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-account-outline text-primary"></i> My Profile <span class="badge badge-pill badge-danger">1</span></a>
                    <a class="dropdown-item" href="<?=url_pesquisa("logout")?>"><i class="dropdown-item-icon mdi mdi-power text-primary"></i>Sign Out</a>

                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</div>